### ISSUE TITLE
Cache does not seem to be working with use-installer: true

### ISSUE THREAD

**Issue by ericbn** [aws-actions/setup-sam#103]
Hi 👋 

I don't see a cache being created for SAM under the GitHub Action Caches in my repository using this action.

I'm using:

```
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
          version: 1.107.0
```

and my workflow run logs constantly show:
```
Cached AWS SAM CLI 1.107.0 to /opt/hostedtoolcache/sam/1.107.0/x64
```

Look like the `@actions/cache` module with the `restoreCache` and `saveCache` functions should be used, instead of `@actions/tool-cache` with `find` and `cacheDir`, in order to actually persistently cache the files.
