### ISSUE TITLE
Dependabot cannot tell me to update

### ISSUE THREAD

**Issue by per-oestergaard** [aws-actions/setup-sam#106]
Dependabot is great at keeping things up to date.

However, as this action specifies SAM CLI's version as an argument like

```yml
      - uses: aws-actions/setup-sam@v2
        with:
          version: 1.120.0
```

dependabot is not able to tell me to update the SAM CLI version.

The solution? One could be to (auto) update the action whenever SAM CLI is updated. A better could be to have dependabot discover this version and suggest an update (https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem).
