### ISSUE TITLE
Example without Docker

### ISSUE THREAD

**Issue by hoffa** [aws-actions/setup-sam#28]
Current documentation only includes the catch-all approach using `--use-container`. This works great on GitHub-hosted runners, but might be less straightforward on self-hosted ones lacking Docker (there is no official `setup-docker` either). It also potentially takes longer than using `setup-node` and `sam build`ing the app right away, as many `setup-*` actions are cached.

Example:

```yaml
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: aws-actions/setup-sam@v0
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - run: sam build
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
```

Maybe have a section for building with Docker, and one without?
