### ISSUE TITLE
Add example to README

### ISSUE THREAD

**Issue by hoffa** [aws-actions/setup-sam#8]
Something like this?

```yaml
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/setup-sam@v0
        with:
          version: 1.18.2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - run: sam build --use-container
      - run: sam deploy --no-fail-on-empty-changeset --no-confirm-changeset
```
