### ISSUE TITLE
Intermittant Setup-Sam Failures

### ISSUE THREAD

**Issue by Bhutania** [aws-actions/setup-sam#91]
Hi 👋🏽 ,

Not sure if this is the right place to post this issue or in actions/runner (or runner-images), but I figured I would post here first to rule out issues with the action itself.

I am experiencing somewhat intermittent failures when trying to setup sam on an ubuntu-22.04 runner from github.

Action Setup:
```
name: Setup sam.

description: Sets up AWS SAM with retries.

runs:
  using: "composite"
  steps:
    - uses: aws-actions/setup-sam@v2
      id: setup1
      continue-on-error: true
      with:
        use-installer: true

    - run: echo "SAM Setup Failed, 10 Second Timeout" && sleep 10
      if: ${{ steps.setup1.outcome == 'failure' }}
      shell: bash

    - uses: aws-actions/setup-sam@v2
      id: setup2
      continue-on-error: true
      if: ${{ steps.setup1.outcome == 'failure' }}
      with:
        use-installer: true

    - run: echo "SAM Setup Failed, 10 Second Timeout" && sleep 10
      if: ${{ steps.setup2.outcome == 'failure' }}
      shell: bash

    - uses: aws-actions/setup-sam@v2
      id: setup3
      if: ${{ steps.setup2.outcome == 'failure' }}
      with:
        use-installer: true
```

Here is a copy of the runner info for the last failure:
```
  Image: ubuntu-22.04
  Version: 20231205.1.0
```
Error message and retries:
```
Run aws-actions/setup-sam@v2
Error: Error:
/usr/bin/unzip -o -q /home/runner/work/_temp/5416c708-9217-4057-8852-a01b225e1e32
Run echo "SAM Setup Failed, 10 Second Timeout" && sleep 10
SAM Setup Failed, 10 Second Timeout
Run aws-actions/setup-sam@v2
Error: Error:
/usr/bin/unzip -o -q /home/runner/work/_temp/4dc53d00-a7c1-471e-bd54-f43ae8e8dd0e
Run echo "SAM Setup Failed, 10 Second Timeout" && sleep 10
SAM Setup Failed, 10 Second Timeout
Run aws-actions/setup-sam@v2
Error: Error:
/usr/bin/unzip -o -q /home/runner/work/_temp/d4efffda-8428-4661-9417-b86ad0e9ab7b
```
Unfortunately because of the issue's intermittent nature, I haven't been able to reproduce with debug logging. I'll keep trying though.

Normally the setup task is fine and has an output like this:
![image](https://github.com/aws-actions/setup-sam/assets/32190247/f98f369b-5468-493d-8ae7-8acdd63b433e)

I would appreciate it someone had any insight into this issue, or could point me in the right direction.

Thanks,
Arnav
