### ISSUE TITLE
Runtime Node20.x support in github actions?

### ISSUE THREAD

**Issue by mkkeems** [aws-actions/setup-sam#92]
@ssenchenko 

With the new version of sam-cli pulled on my local machine, i'm able to successfully build sam apps with runtime set to node20.x

However, the issue i'm having is when i try to deploy the sam app with **github actions.**
Here is a bit of the **github workflow pipline.yaml** I have:
 ```
 build-and-deploy-dev:
    if: github.ref == 'refs/heads/dev'
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - run: sam build --template ${SAM_TEMPLATE} --use-container
```
..and so on.
This is where i get the error in **github actions**: 
```
Build Failed
Error: 'nodejs20.x' runtime is not supported
```
How should i update the `.github/workflows/pipeline.yaml` file in order for the sam app to be successfully built when the runtime is set to `node20.x` in the template.yaml?

**Comment by mkkeems** [comment]
Ahh, the issue was not with aws-actions/setup-sam@v2.

After updating the following actions, I was able to successfully deploy the sam-app via github actions with runtime set to `nodejs20.x`
- actions/checkout@v3 =>  **actions/checkout@v4**
- aws-actions/configure-aws-credentials@v1 => **aws-actions/configure-aws-credentials@v4**

```
...
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - run: sam build --template ${SAM_TEMPLATE} --use-container

      - name: Assume the dev pipeline user role
        uses: aws-actions/configure-aws-credentials@v4
...
```

Cheers! 😄
